### ISSUE TITLE
Usage with vault.yml

### ISSUE THREAD

**Issue by mockey** [louim/bedrock-site-protect#11]
This is really a useful addition, thanks for that.
In the README it says:

> You may want to add the htpasswd block in the vault.yml file so password will be encrypted.

But that doesn't work. I don't know anything about Ansible syntax but I presume it's because the variable in `vault.yml` is called `vault_wordpress_sites` and not `wordpress_sites`. Would simply changing the var name everywhere work already or is there more to it? In general I think the password should go into vault.yml.

**Comment by tmugford** [comment]
I’m having the same issue. I’ve added the entire block to the environment specific `vault.yml`, and it’s completely ignored when running the playbook. Works great if it’s in `wordpress_sites.yml`.

**Comment by mockey** [comment]
As a quick and dirty hack I do it like this now:
in `group_vars/staging/wordpress_sites.yml`:
```
    htpasswd:
      - name: the_name
        password: "{{ vault_htpassword }}"
```
in `group_vars/staging/vault.yml`:
```
vault_htpassword: the_password
```

**Comment by louim** [comment]
Hey! Been a long time since I used Trellis. Solution proposed by @mockey looks good as a safe workaround to protect the password. 

The real fix would probably be to lookup in both dicts (`vault_wordpress_sites` and `wordpress_sites`) to check which one has the key `htpasswd`, set the dict as a variable, and use it throughout [the playbook](https://github.com/louim/bedrock-site-protect/blob/master/tasks/manage.yml). 

If one of you want to try it, I'll gladly accept a PR. A PR for the doc in the meantime would also be cool! 😄

**Comment by tmugford** [comment]
Thanks @mockey. I’d come to the same conclusion myself.

@louim I’ll take a look at this when I’ve got my current project out of the way. Ansible is completely new to me, so I’ll need to dig through the docs.

**Comment by mockey** [comment]
Hey @louim! I also use Trellis only once in a while, but when I do I always include your role for staging.

> The real fix would probably be to lookup in both dicts (vault_wordpress_sites and wordpress_sites) to check which one has the key htpasswd, set the dict as a variable, and use it throughout the playbook.

The problem with this is that you use `site_hosts.0.canonical` from `wordpress_sites` for the htpasswd filename ATM. But I think that could be changed to `item.key`, couldn't it? It goes into `{{ item.key }}.conf` anyway.
Also I think every password in Trellis is supposed to go into the vault files, so why not use `vault_wordpress_sites` straightaway?

**Comment by mockey** [comment]
I think I know now, why you use `item.0.site_hosts.0.canonical` instead of `item.key`. It seems you can't get the dict keys when using `with_subelements`. Too bad...

**Comment by louim** [comment]
This has been fixed in https://github.com/louim/bedrock-site-protect/pull/12
