### ISSUE TITLE
TASK [bedrock-site-protect : Set htpasswd] - Failing

### ISSUE THREAD

**Issue by michelecocuccio** [louim/bedrock-site-protect#13]
Hello I am using the latest version of Trellis. I have never had problems with bedrock-site-protect but something is not working now. I haven't done anything different from the previous projects.
This is what I am getting:

TASK [bedrock-site-protect : Set htpasswd] *************************************************************************************************
task path: /Users/michelecocuccio/Desktop/NUWebsites/Hireworks/trellis/vendor/roles/bedrock-site-protect/tasks/manage.yml:9
System info:
  Ansible 2.4.0.0; Darwin
  Trellis at "Add MariaDB 10.2 PPA"
---------------------------------------------------
template error while templating string: Missing end of comment tag. String:
!aVdPzDfe{h6rxNUM3{3Qn{#.?r*9X}4r-w%dj-:I`mFBZ>4ay4k8UBPudnizV8$
fatal: [138.68.151.12]: FAILED! => {
    "failed": true
}

The password is just a string with a number and an exclamation mark and the user is just a string as well:

    htpasswd:
      - name: Testing
        password: Magic123!

Any idea on what could be wrong?
Thanks

**Comment by louim** [comment]
Hey! I think this might not be related to bedrock-site-protect. The string 
```
!aVdPzDfe{h6rxNUM3{3Qn{#.?r*9X}4r-w%dj-:I`mFBZ>4ay4k8UBPudnizV8$
```
contains the characters `{#` which the templating engine interpret as a comment opening, and it doesn’t find the matching closing. 

My best guess is that string is one of Wordpress auto generated salts. You just have to change the `{#` to something else and it should work.

**Comment by michelecocuccio** [comment]
I am so sorry if I opened it here.
Thanks a lot for replying so fast. I will try to re-generate the salts.

**Comment by louim** [comment]
No problem! Happy to see that people are using my extension 😁
