### ISSUE TITLE
passlib missing from Trellis install

### ISSUE THREAD

**Issue by smaboshe** [louim/bedrock-site-protect#15]
In the current (https://github.com/roots/trellis/commit/f979bec7c3b207db9b5cabfe12e244307c8bcb37) version of Trellis, I consistently get the following error while running `vagrant up --provision`:

```
TASK [bedrock-site-protect : Set htpasswd] *************************************
System info:
  Ansible 2.7.5; Vagrant 2.2.2; Linux
  Trellis version (per changelog): "Fix Vagrant trigger path"
---------------------------------------------------
This module requires the passlib Python library
```
The error is fixed by requiring the library explicitly in `trellis/group_vars/all/main.yml` :

```
...
apt_packages_custom:
  python3-passlib: present
...
```
Ref:  https://discourse.roots.io/t/provisioning-with-optipng-gifsicle-and-libjpeg-progs/10005/4

I had never needed to require this library before-hand. Is there a way to have this library installed automatically as a dependency when `bedrock-site-protect` is being installed (or is this a Trellis issue)?

**Comment by louim** [comment]
Hey!
We install `python-passlib` here: 
https://github.com/louim/bedrock-site-protect/blob/4f58b8cf61505c1ed56f36322fed8d9fb2243608/tasks/install.yml#L7-L8
Maybe we need to install `python3-passlib` now?

**Comment by smaboshe** [comment]
I see. Perhaps we do.

Trellis now installs Ubuntu 18.04. Just checked my VM and both Python 2 (Python 2.7.15rc1) and Python 3 (Python 3.6.7) are present.

I can't tell which Python Trellis is using by default but could help you find out.

**Comment by smaboshe** [comment]
The thread with the Trellis team on this issue is here:
https://discourse.roots.io/t/which-version-of-python-does-trellis-use/14409/2

Does this help?

**Comment by louim** [comment]
Hey!
I pushed a branch with a potential fix.

Can you try it and let me know if it works?
Use this in you requirements.yml:

```
- name: bedrock-site-protect
  src: https://github.com/louim/bedrock-site-protect
  version: improvement/support-python-3
```

Ideally you would need a clean vm, as the package might already be installed by your previous `apt_packages_custom`. You can also uninstall the package manually and check if it work.

Let me know how it goes.

**Comment by alex-galey** [comment]
I had the same issue as @smaboshe
Your fix is working like a charm @louim

**Comment by smaboshe** [comment]
Thank you @louim. The fix works as advertised :slightly_smiling_face:

**Comment by louim** [comment]
Hey all!

I just pushed version 2.0.0 to the galaxy hub, so you now should be able to install the package by adding:
```
- name: bedrock-site-protect
  src: louim.bedrock-site-protect
  version: 2.0.0
```

Have a great day! 🎉
