### ISSUE TITLE
Deprecation warning : Include

### ISSUE THREAD

**Issue by alex-galey** [louim/bedrock-site-protect#17]
`[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.`

In tasks/main.yml line 3 and 9

Would be ready to submit a PR but I don't know whether import_tasks or include_tasks is appropriate

**Comment by louim** [comment]
Hey! `import_tasks` is the one we want to use because we don’t need dynamic inclusion. 

I’d be happy to merge a PR 🎉
