### ISSUE TITLE
Installed role, added to server.yml, re-deployed, this role does not appear to run

### ISSUE THREAD

**Issue by qbunt** [louim/bedrock-site-protect#2]
Hey there, this looks like great work, I'm really eager to use it, however, I can't get it to run. I've added the role to the requirements.yml file, installed the role (I can see it inside `vendor/roles` set up by the `ansible.cfg` file) and added the appropriate line to server.yml. Do I simply need to run a deployment to that environment for this playbook to fire? Maybe I'm misinterpreting your readme, I'd appreciate any input here, thanks!

**Comment by louim** [comment]
If should activate if you reprovision the environment ex: `ansible-playbook server.yml -e env=staging`

**Comment by qbunt** [comment]
heh, I think you and I both reached the same conclusion at the same time. Worked great. I may issue a PR shortly with some clarification on the readme file, that sound alright?

**Comment by louim** [comment]
Sure thing! :+1:
