### ISSUE TITLE
No requirements.yml

### ISSUE THREAD

**Issue by stefthoen** [louim/bedrock-site-protect#20]
New Trellis projects have a `requirement.txt` file. The `requirement.yml` file seems to be gone. Does this Ansible role still work or is it outdated?

**Comment by louim** [comment]
Hey! 

The requirement file has been renamed from `requirement.yml` to `galaxy.yml` in Trellis. If nothing else changed, you should be good to go by adding the package there. That would also mean the install command would be `ansible-galaxy install -r galaxy.yml`. Let me know how it goes!

**Comment by devotoare** [comment]
Just confirming this works, though would be nice to see in the docs so the project looks like it's still alive :)

**Comment by louim** [comment]
@devotoare Thanks for confirming! Would you be interested in doing a PR to update the readme?

**Comment by devotoare** [comment]
@louim all set :)

Thanks for the project!

**Comment by stefthoen** [comment]
@louim Just wanted to let you know that I also got  this to work (thank you @devotoare for the Readme update). In the Readme you mention that I can also add the `htpasswd` block to `vault.yml`. Could you be a bit more specific where I should add it exactly? I tried to remove the `htpasswd` block `wordpress_sites.yml` and tried to add the following:
```
htpasswd: 
  - name: user
  - pass: secret
```

To my `staging/vault.yml` above `vault_wordpress_sites`, below vault_wordpress_sites > example.com` (so it's a sibling to the `env` variable) and below the `env` variable, but I'm having no luck.

**Comment by devotoare** [comment]
@stefthoen  Haven't tested but it should be something like this:

wordpress_sites.yml:
```
htpasswd: 
  - name: "{{ htpass_user }}"
  - pass: "{{ htpass_pass }}"
```

group_vars/all/vault.yml:
```
vault_wordpress_env_defaults:
  htpass_user: username
  htpass_pass: password
```

or if you want it just in staging:
group_vars/staging/vault.yml:
```
vault_wordpress_sites:
  example.com:
    htpass_user: username
    htpass_pass: password
    env:
      ....
```
