### ISSUE TITLE
Documentation + Version Number

### ISSUE THREAD

**Issue by samburgers** [louim/bedrock-site-protect#7]
Hi, 

Running Ansible install fails for me unless version number is set explicitly to `1.1.0` 

The readme currently says `1.0` which might be worth fixing.

`the specified version (1.1) of bedrock-site-protect was not found in the list of available versions`

ta

**Comment by louim** [comment]
You are right, I just updated the readme to match the tag version of the package (1.1.0). 

Thanks for reporting!
