### ISSUE TITLE
Gets "the key htpasswd should point to a list"

### ISSUE THREAD

**Issue by alexkerber** [louim/bedrock-site-protect#9]
When I try to run "ansible-playbook server.yml -e env=staging"

**Comment by louim** [comment]
Can you paste your `wordpress_sites` config here?

**Comment by alexkerber** [comment]
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: stage.example
        # redirects:
        #   - otherdomain.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:devrepro/repro.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: staging
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
    htpasswd:
      name: user2
      password: secret2

**Comment by louim** [comment]
`htpasswd` should look like that:

```
htpasswd:
  - name: user
    password: secret
```

notice the dash `-`  before name

**Comment by alexkerber** [comment]
I've tried that too. Trying again, please hold.

**Comment by alexkerber** [comment]
What, lol it works now! No idea why because I did this before. Thanks, and thanks for a great function for Trellis!
